### ISSUE TITLE
Feasibility Study has finished

### ISSUE THREAD

**Issue by 8rV1n** [Dawn-Team/dawn#2]
Feasibility Study has been finished ,and the [report file](https://github.com/Dawn-Team/dawn/blob/FeasibilityAnalysis/Doc/1.Feasibility%20Study%20Report.docx) now is under pre-publish state.
We will start PancakeofMountHuang only if we finished the Review process about the documents.
@Ash-Morgan , Please make a quick review about the files and the [Project Tab](https://github.com/Dawn-Team/dawn/projects/1).

**Comment by Ash-Morgan** [comment]
Documents have reviewed. @ArvinSiChuan

**Comment by 8rV1n** [comment]
@Dawn-Team/pancakeofmounthuang Finished?
